version: '1'
services:
  web:
    container_name: FRONTENDAPP
    hostname: frontend_app
    ports:
      - "3000:3000"   
    image: frontendapp:0.1
    # build:
    #   context: .
    #   dockerfile: Dockerfile   
    environment:
      - API_URL=${API_URL}
      - THEME=${THEME}
    depends_on:
      - backend
 
  backend:
    container_name: JDBC
    hostname: jdbc
    ports:
      - "8080:8080"
    image: myapp:0.1
    environment:
      - DB_HOST=$DB_HOST
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USERNAME=$DB_USERNAME
      - DB_NAME=$DB_NAME