version: '1'
services:
  web:
    container_name: FRONTENDAPP
    hostname: frontend_app
    ports:
      - "3000:3000"		
    image: frontend_app
    build: 
      context: .
      dockerfile: Dockerfile   
    environment: 
      - API_URL=http://localhost:8080/api/test
    
