name: pa11yci

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run pally
    - run: | 
      npm install -g pa11y-ci
      pa11y-ci
